name: Inferencia (manual)

on:
  workflow_dispatch:
    inputs:
      horizonte_dias:
        description: "Horizonte en días (default 120)"
        required: false
        default: "120"

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m src.download_release --owner Supervision-Inbound --repo IAs

      - name: Run inference
        env:
          HORIZONTE_DIAS: ${{ github.event.inputs.horizonte_dias }}
        run: |
          python -m src.main --horizonte "${HORIZONTE_DIAS:-120}"

      - name: Commit JSON outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/*.json || true
          git commit -m "Inferencias $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push || true

      - name: Upload JSON artifacts
        uses: actions/upload-artifact@v4
        with:
          name: salidas-json
          path: public/*.json
